// Mock data for the AI Sales platform
// Simulates customer data for a massage/spa physical store

export const mockCustomers = [
  {
    id: '1',
    name: '陈丽华',
    avatar: null,
    phone: '138****8812',
    wechatId: 'lily_chen88',
    source: 'wechat',
    lifecycleStatus: 'closed',
    intentScore: 4.8,
    valueScore: 4.5,
    demandScore: 3.9,
    satisfactionScore: 4.7,
    relationScore: 4.2,
    silentDays: 0,
    aiSummary: '陈丽华是一位高价值VIP客户，过去3个月消费6次，偏好精油SPA和泰式按摩。上次来店体验了新推出的热石疗法，非常满意，主动询问了会员卡充值优惠。沟通风格直接，喜欢提前预约固定技师。',
    lastInteractionAt: '2026-04-07T10:30:00Z',
    lastKeyQuestion: '会员卡充值有什么优惠？',
    assignedTo: '小王',
    tags: [
      { name: 'VIP客户', category: 'lifecycle', color: '#07C160' },
      { name: '高意向', category: 'intent', color: '#1677FF' },
      { name: '精油SPA', category: 'custom', color: '#7C3AED' },
      { name: '已成交', category: 'lifecycle', color: '#07C160' },
    ],
    conversations: [],
  },
  {
    id: '2',
    name: '张伟强',
    avatar: null,
    phone: '139****3345',
    wechatId: 'zhangwq_2023',
    source: 'wechat',
    lifecycleStatus: 'following',
    intentScore: 3.8,
    valueScore: 3.5,
    demandScore: 4.2,
    satisfactionScore: 0,
    relationScore: 2.1,
    silentDays: 5,
    aiSummary: '张伟强是一位潜力客户，3天前添加了企微，咨询过肩颈按摩套餐价格和技师资质。对价格比较关注，询问了是否有新客体验价。目前处于跟进阶段，建议推送新客优惠套餐促成首次到店。',
    lastInteractionAt: '2026-04-02T15:20:00Z',
    lastKeyQuestion: '新客体验价是多少？可以先试一次吗？',
    assignedTo: '小李',
    tags: [
      { name: '跟进中', category: 'lifecycle', color: '#07C160' },
      { name: '高意向', category: 'intent', color: '#1677FF' },
      { name: '肩颈按摩', category: 'custom', color: '#7C3AED' },
      { name: '价格敏感', category: 'risk', color: '#FF8C00' },
    ],
    conversations: [],
  },
  {
    id: '3',
    name: '李雪梅',
    avatar: null,
    phone: '136****7721',
    wechatId: 'xuemei_li',
    source: 'wechat',
    lifecycleStatus: 'silent',
    intentScore: 2.5,
    valueScore: 3.8,
    demandScore: 2.0,
    satisfactionScore: 3.5,
    relationScore: 2.8,
    silentDays: 22,
    aiSummary: '李雪梅曾是活跃客户，过去半年消费过3次，偏好面部护理和头部按摩。最近22天未有任何互动。上次来店时提到工作较忙，可能需要适时发送关怀消息唤醒。历史消费金额中等偏高。',
    lastInteractionAt: '2026-03-16T09:15:00Z',
    lastKeyQuestion: '最近太忙了，下次有时间再约。',
    assignedTo: '小王',
    tags: [
      { name: '沉默客户', category: 'risk', color: '#FF4D4F' },
      { name: '面部护理', category: 'custom', color: '#7C3AED' },
      { name: '高价值', category: 'lifecycle', color: '#07C160' },
    ],
    conversations: [],
  },
  {
    id: '4',
    name: '王建国',
    avatar: null,
    phone: '135****9956',
    wechatId: 'wjg_boss',
    source: 'wechat',
    lifecycleStatus: 'closed',
    intentScore: 4.2,
    valueScore: 4.9,
    demandScore: 3.5,
    satisfactionScore: 4.8,
    relationScore: 4.5,
    silentDays: 2,
    aiSummary: '王建国是店铺最高价值客户之一，累计消费超过2万元。偏好足部按摩和中医理疗，每周固定来店1-2次。今天下午3点有预约足部按摩（90分钟），技师指定刘师傅。非常注重服务品质，推荐新服务接受度高。',
    lastInteractionAt: '2026-04-05T18:00:00Z',
    lastKeyQuestion: '刘师傅今天下午有空吗？我想约3点。',
    assignedTo: '小王',
    tags: [
      { name: 'VIP客户', category: 'lifecycle', color: '#07C160' },
      { name: '已成交', category: 'lifecycle', color: '#07C160' },
      { name: '足部按摩', category: 'custom', color: '#7C3AED' },
      { name: '高频', category: 'intent', color: '#1677FF' },
    ],
    conversations: [],
  },
  {
    id: '5',
    name: '刘芳',
    avatar: null,
    phone: '137****6623',
    wechatId: 'liufang_2024',
    source: 'wechat',
    lifecycleStatus: 'new',
    intentScore: 3.0,
    valueScore: 2.0,
    demandScore: 3.5,
    satisfactionScore: 0,
    relationScore: 1.0,
    silentDays: 0,
    aiSummary: '刘芳是今天新添加的客户，通过朋友推荐了解到店铺。简单问了一下有什么服务，尚未深入沟通。属于初步意向阶段，建议发送店铺服务介绍和新客优惠。',
    lastInteractionAt: '2026-04-07T14:10:00Z',
    lastKeyQuestion: '你们家有什么服务啊？朋友推荐来的。',
    assignedTo: null,
    tags: [
      { name: '新客', category: 'lifecycle', color: '#07C160' },
      { name: 'AI接待', category: 'status', color: '#999999' },
      { name: '👋', category: 'status', color: '#FF8C00' },
    ],
    conversations: [],
  },
  {
    id: '6',
    name: '赵明辉',
    avatar: null,
    phone: '133****4478',
    wechatId: 'zhaomh_work',
    source: 'wechat',
    lifecycleStatus: 'trial',
    intentScore: 3.5,
    valueScore: 3.0,
    demandScore: 4.0,
    satisfactionScore: 3.8,
    relationScore: 2.5,
    silentDays: 8,
    aiSummary: '赵明辉体验过一次泰式按摩，反馈比较满意但觉得价格偏高。8天未联系，属于观望期。曾询问是否有季卡或月卡套餐，建议发送套餐优惠促进二次消费。',
    lastInteractionAt: '2026-03-30T11:45:00Z',
    lastKeyQuestion: '有没有月卡之类的优惠？单次感觉有点贵。',
    assignedTo: '小李',
    tags: [
      { name: '试用中', category: 'lifecycle', color: '#07C160' },
      { name: '泰式按摩', category: 'custom', color: '#7C3AED' },
      { name: '价格敏感', category: 'risk', color: '#FF8C00' },
    ],
    conversations: [],
  },
  {
    id: '7',
    name: '周婷',
    avatar: null,
    phone: '158****2234',
    wechatId: 'zhouting_88',
    source: 'wechat',
    lifecycleStatus: 'silent',
    intentScore: 1.8,
    valueScore: 3.2,
    demandScore: 1.5,
    satisfactionScore: 2.5,
    relationScore: 1.8,
    silentDays: 35,
    aiSummary: '周婷已超过35天未联系，之前消费过2次芳疗按摩。上次来店时服务体验有些小问题（等候时间较长），虽然当时已解决但可能影响了回访意愿。建议发送歉意+特别优惠唤醒。',
    lastInteractionAt: '2026-03-03T16:30:00Z',
    lastKeyQuestion: null,
    assignedTo: '小王',
    tags: [
      { name: '沉默客户', category: 'risk', color: '#FF4D4F' },
      { name: '未成交', category: 'risk', color: '#FF4D4F' },
      { name: '芳疗按摩', category: 'custom', color: '#7C3AED' },
    ],
    conversations: [],
  },
  {
    id: '8',
    name: '孙国强',
    avatar: null,
    phone: '186****5567',
    wechatId: 'sun_gq',
    source: 'wechat',
    lifecycleStatus: 'closed',
    intentScore: 4.0,
    valueScore: 4.3,
    demandScore: 3.8,
    satisfactionScore: 4.5,
    relationScore: 3.8,
    silentDays: 3,
    aiSummary: '孙国强是常客，喜欢运动后来做深度肌肉放松按摩。消费稳定，每两周来一次。最近提到腰不太舒服，可能需要推荐中医理疗项目。态度友善，对推荐接受度高。',
    lastInteractionAt: '2026-04-04T20:15:00Z',
    lastKeyQuestion: '我最近腰有点不舒服，你们有没有针对性的项目？',
    assignedTo: '小李',
    tags: [
      { name: '已成交', category: 'lifecycle', color: '#07C160' },
      { name: '运动放松', category: 'custom', color: '#7C3AED' },
      { name: '高价值', category: 'lifecycle', color: '#07C160' },
      { name: 'AI接待', category: 'status', color: '#999999' },
    ],
    conversations: [],
  },
];

export const mockMessages = {
  '1': [
    { id: 'm1', direction: 'inbound', senderType: 'customer', contentType: 'text', content: '小王，我想问下你们会员卡充值有什么优惠啊？', createdAt: '2026-04-07T10:25:00Z' },
    { id: 'm2', direction: 'outbound', senderType: 'ai', contentType: 'text', content: '陈姐您好呀~✨ 最近刚好有一个充值活动呢！充3000送500，充5000送1000，而且送的余额不限时间使用哦。以您的消费频率，充5000最划算啦，相当于打了8.3折呢~ 要不要我帮您预留一个名额？', createdAt: '2026-04-07T10:25:30Z' },
    { id: 'm3', direction: 'inbound', senderType: 'customer', contentType: 'text', content: '充5000送1000？那挺不错的，我考虑一下', createdAt: '2026-04-07T10:28:00Z' },
    { id: 'm4', direction: 'outbound', senderType: 'ai', contentType: 'text', content: '好的陈姐~这个活动名额有限呢，月底就截止啦。您下次来店的时候可以直接办理，我提前帮您准备好资料~ 对了，您上次体验的热石疗法感觉怎么样呀？', createdAt: '2026-04-07T10:28:20Z' },
    { id: 'm5', direction: 'inbound', senderType: 'customer', contentType: 'text', content: '热石疗法很好，我很喜欢。下周三下午我过来，帮我约一下', createdAt: '2026-04-07T10:30:00Z' },
  ],
  '2': [
    { id: 'm6', direction: 'inbound', senderType: 'customer', contentType: 'text', content: '你好，我想了解一下你们的肩颈按摩套餐', createdAt: '2026-04-02T15:10:00Z' },
    { id: 'm7', direction: 'outbound', senderType: 'ai', contentType: 'text', content: '您好呀~欢迎咨询！我们的肩颈按摩套餐有几个选择：\n\n🌿 基础肩颈放松 60分钟 ¥298\n💆 深度肩颈修复 90分钟 ¥458\n✨ 尊享肩颈理疗 120分钟 ¥698\n\n每个套餐都包含精油和热敷哦~ 新客还有首次体验价85折优惠呢！您主要是哪方面不太舒服？', createdAt: '2026-04-02T15:10:30Z' },
    { id: 'm8', direction: 'inbound', senderType: 'customer', contentType: 'text', content: '新客体验价是多少？可以先试一次吗？', createdAt: '2026-04-02T15:15:00Z' },
    { id: 'm9', direction: 'outbound', senderType: 'ai', contentType: 'text', content: '当然可以呀~新客体验价的话，基础肩颈放松只要¥253，深度修复是¥389！我们技师都是持证上岗的，很多客人体验完都成了常客呢😊 您什么时候方便过来体验？我帮您预约一个好时段~', createdAt: '2026-04-02T15:15:30Z' },
    { id: 'm10', direction: 'inbound', senderType: 'customer', contentType: 'text', content: '好的我再看看，有时间了联系你', createdAt: '2026-04-02T15:20:00Z' },
  ],
  '5': [
    { id: 'm11', direction: 'inbound', senderType: 'customer', contentType: 'text', content: '你们家有什么服务啊？朋友推荐来的。', createdAt: '2026-04-07T14:10:00Z' },
    { id: 'm12', direction: 'outbound', senderType: 'ai', contentType: 'text', content: '您好呀~欢迎欢迎！感谢朋友的推荐🎉\n\n我们主要提供这些服务：\n💆 中式/泰式/精油按摩\n🧖 面部护理\n🦶 足部按摩\n🌿 芳疗SPA\n🔥 热石/刮痧/拔罐理疗\n\n都是持证技师一对一服务，环境也很舒适哦~ 新客首次到店还有85折优惠！\n\n方便问一下，您是哪个方面有需求呀？我可以帮您推荐最适合的项目~', createdAt: '2026-04-07T14:10:20Z' },
  ],
};

export const mockAppointments = [
  {
    id: 'a1',
    customerId: '4',
    customerName: '王建国',
    serviceType: 'foot_massage',
    serviceName: '足部按摩（90分钟）',
    appointmentAt: '2026-04-07T15:00:00Z',
    duration: 90,
    room: 'VIP A3',
    staffName: '刘师傅',
    status: 'confirmed',
    reminderSentAt: null,
    reminderHours: 3,
  },
  {
    id: 'a2',
    customerId: '1',
    customerName: '陈丽华',
    serviceType: 'hot_stone',
    serviceName: '热石疗法（60分钟）',
    appointmentAt: '2026-04-09T14:00:00Z',
    duration: 60,
    room: 'SPA B2',
    staffName: '王技师',
    status: 'pending',
    reminderSentAt: null,
    reminderHours: 3,
  },
];

export const mockTasks = [
  {
    id: 't1',
    customerId: '3',
    customerName: '李雪梅',
    title: '沉默客户唤醒 - 李雪梅',
    triggerSource: 'sop',
    triggerReason: '客户已沉默22天，历史消费中等偏高，偏好面部护理。建议发送春季面部护理优惠+店铺新环境照片唤醒。',
    taskType: 'combo',
    content: '雪梅姐，好久不见啦~最近我们店新升级了环境，还引进了最新的日式面部护理仪器，效果特别好呢✨ 给您留了一个老客专属体验名额，限时享受7折优惠哦~ 想不想过来放松一下？',
    scheduledAt: '2026-04-08T10:00:00Z',
    approvalStatus: 'pending',
    executeStatus: 'draft',
  },
  {
    id: 't2',
    customerId: '7',
    customerName: '周婷',
    title: '沉默客户唤醒 - 周婷',
    triggerSource: 'sop',
    triggerReason: '客户已沉默35天，上次来店体验有等候时间较长的问题。建议发送歉意关怀+特别补偿优惠。',
    taskType: 'text',
    content: '周婷您好~很抱歉上次给您造成了不好的体验，我们已经优化了预约流程，现在完全不需要等候了呢。为了表达歉意，特别为您准备了一次免费的芳疗按摩体验，随时欢迎您过来~ 🌸',
    scheduledAt: '2026-04-08T14:00:00Z',
    approvalStatus: 'pending',
    executeStatus: 'draft',
  },
  {
    id: 't3',
    customerId: '2',
    customerName: '张伟强',
    title: '高意向跟进 - 张伟强',
    triggerSource: 'ai',
    triggerReason: '客户5天前询问了新客体验价，表现出明确兴趣但未预约。建议发送限时优惠+到店引导。',
    taskType: 'text',
    content: '张先生您好~上次给您介绍的肩颈按摩体验价还给您保留着呢😊 这周末我们技师时间比较充裕，效果最好的深度肩颈修复也可以给您新客价¥389体验一次。要不要我帮您约这个周六下午？',
    scheduledAt: '2026-04-09T09:00:00Z',
    approvalStatus: 'approved',
    executeStatus: 'scheduled',
  },
];

export const mockWorkflowTasks = [
  {
    id: 'w1',
    time: '10:00',
    type: 'report',
    target: '管理群',
    description: '每日运营报告',
    color: '#E8E8E8',
    icon: '📊',
  },
  {
    id: 'w2',
    time: '10:30',
    type: 'marketing',
    target: '全部客户',
    description: '春季SPA新品推荐',
    color: '#FFF4E6',
    icon: '🌸',
  },
  {
    id: 'w3',
    time: '12:00',
    type: 'reminder',
    target: '王建国',
    description: '预约提醒：足部按摩 15:00',
    color: '#E6F7EE',
    icon: '⏰',
  },
  {
    id: 'w4',
    time: '14:00',
    type: 'follow',
    target: '周婷',
    description: '沉默客户唤醒消息',
    color: '#E6F0FF',
    icon: '💬',
  },
];

export const mockMaterials = [
  { id: 'mat1', title: '春季SPA优惠海报', type: 'image', tags: '优惠,SPA,春季' },
  { id: 'mat2', title: '店铺环境实拍视频', type: 'video', tags: '环境,宣传' },
  { id: 'mat3', title: '新客欢迎话术', type: 'text', content: '您好呀~欢迎关注我们！我们是...', tags: '话术,新客' },
  { id: 'mat4', title: '技师团队介绍', type: 'text', content: '我们的技师团队均持有国家认证...', tags: '团队,介绍' },
  { id: 'mat5', title: '服务项目列表', type: 'link', tags: '服务,项目' },
  { id: 'mat6', title: '客户好评截图', type: 'image', tags: '评价,口碑' },
];

export const mockPersona = {
  companyName: '悦心养生馆',
  greeting: '你好，我是悦心养生馆的小悦',
  businessScope: '提供专业的按摩、SPA、面部护理、足疗等养生服务。拥有持证技师团队，VIP独立包间，环境温馨舒适。服务特色包括中式按摩、泰式按摩、精油SPA、热石疗法、面部护理等。面向追求品质生活的都市白领和高端客户群。',
  personaStyle: `- **身份**：你是悦心养生馆的专属顾问小悦，不是机器人，是一个温暖、专业的服务人员
- **性格**：热情亲切、专业细心，善于倾听客户需求
- **语言风格**：口语化，使用接地气的表达，简短、直击要害的回复风格
- **语言长度**：回复简洁明了，每次回复总字数不要超过100字
- **沟通目标**：让客户感受到专业关怀，自然引导预约和消费`,
  dialogRestriction: `### 语言风格
- **语气**：温暖热情/专业温和
- **避免**：AI式过渡语言、自我解释、总结性表达
- **口语化**：使用"呀""呢""哦""啦"等自然语气词
- 回复格式：仅使用纯文本，不要使用markdown格式
- 不要每句话都加句号，结尾没有句号更自然`,
};

export const mockReport = {
  reportDate: '2026-04-07',
  totalMessages: 47,
  aiReplies: 38,
  avgResponseTime: 28,
  newHighIntentCount: 2,
  silentActivated: 1,
  pendingApprovals: 3,
  totalCustomers: 156,
  totalGroups: 12,
  newCustomers: 3,
  sentMessages: 38,
  receivedMessages: 47,
  highFreqKeywords: ['按摩', '预约', '价格', 'SPA', '优惠', '时间'],
  keyCustomers: [
    { name: '张伟强', reason: '高意向，5天未跟进', action: '发送体验优惠' },
    { name: '李雪梅', reason: '沉默22天，历史高价值', action: '发送唤醒消息' },
    { name: '刘芳', reason: '今日新客，待深入沟通', action: '发送服务介绍' },
  ],
  pendingTagApprovals: 4,
  pendingTaskApprovals: 2,
  aiSummary: '今日运营整体稳定。新增3位客户，其中刘芳通过朋友推荐加入，建议重点跟进。张伟强意向明确但5天未联系，建议尽快发送体验优惠促成首单。王建国今日下午有预约，需确认房间和技师准备。沉默客户李雪梅和周婷已生成唤醒任务待审批。',
  aiSuggestions: [
    { title: '紧急跟进张伟强', desc: '高意向客户超过5天未联系，有流失风险', link: '查看客户' },
    { title: '审批沉默唤醒任务', desc: '2条沉默客户唤醒任务待审批', link: '去审批' },
    { title: '准备王建国预约', desc: '今日15:00足部按摩预约，请确认VIP A3房间', link: '查看预约' },
  ],
};
